import{scoreSticks,move}from'./rules.mjs';import{portraitPosition,swipeDirection}from'./handbook.mjs';
const $=id=>document.getElementById(id),G='gold',D='dark';
const state={page:0,route:1,faces:[true,true,false,false],swap:false,group:true,groupMoved:false,special:'water',water:false,ending:28,endMoved:false,exit:28,exitScore:3,exited:new Set()};
const pages=[
 {word:'路线',title:'三十格，一条路',lead:'沿着蛇形路线前进，最终把自己的棋带离棋盘。点格子，看看路线怎么转弯。',detail:`<h2>把棋盘竖过来看</h2><p>这里将实体的三行十列棋盘顺时针旋转 90°，方便单手竖屏查看。编号和走法没有改变。</p><p>从右上角 1 格向下，到 10 格转入中列，向上走到 20，再转入左列，一路走到 30。</p><h3>开局怎么摆？</h3><p>两个人各拿 5 枚棋，深浅交替放在 1–10 格。下图按编号显示，方便照着摆。</p><div class="setup-rack">${Array.from({length:10},(_,i)=>`<span><small>${i+1}</small><i class="pawn ${i%2?'':'dark'}"></i></span>`).join('')}</div><p class="fine">上方的单枚蓝色棋只是路线指示，不是完整对局。点击任意格不会消耗回合。</p>`},
 {word:'掷棒',title:'四根棒，五种点数',lead:'点一根棒就翻一面。浅面朝上的数量，决定这一步走多远。',detail:`<h2>先数浅面</h2><p>浅色代表未涂色面，深色代表涂色面。四根都朝深面时，计作 5 步。</p><div class="score-table"><span>浅面</span><span>步数</span><span>还能再掷</span><b>0</b><b>5</b><b>是</b><b>1</b><b>1</b><b>是</b><b>2</b><b>2</b><b>否</b><b>3</b><b>3</b><b>否</b><b>4</b><b>4</b><b>是</b></div><h3>什么时候换人？</h3><p>掷出 1、4、5，走完后还可以再掷一次；掷出 2、3，走完便轮到对方。</p><p class="fine">这个图解可以随意翻面，真实对局则一起抛出四根棒，以落地结果计步。</p>`},
 {word:'交换',title:'相遇，就交换位置',lead:'让金棋走 4 步，到达那枚单独的深色棋。看看两枚棋各自去了哪里。',detail:`<h2>对方回到你的出发格</h2><p>普通情况下，落到对方棋占据的格子，两枚棋交换位置。</p><p>这一步从 12 格到 16 格：金棋走到 16，深色棋换到 12。它仍然留在棋盘上。</p><h3>不是每一枚都能吃</h3><p>相邻同色棋，以及 15 和 26 格上的棋受到保护，不能交换。下一页可以直接试一试。</p><p class="fine">示意图只保留与当前动作有关的棋。中间经过的格子，不是落点。</p>`},
 {word:'保护',title:'结伴的棋，更安全',lead:'切换“有同伴”和“独自一枚”，再尝试同一个落点。',detail:`<h2>相邻，就互相保护</h2><p>同色棋相邻时，不能被交换。这里按路线编号连续来展示：11 和 12 格上的深色棋互相保护。</p><p>当 12 格的同伴移开，11 格的深色棋才变成可以交换的孤立棋。</p><h3>这不是整段封路</h3><p>本版规则只禁止交换受保护的棋，没有“三枚棋挡住整条路线”的条款。</p><p class="fine">原文只说相邻同色棋；本手册以沿行进路线连续的棋来演示，不混用其他版本的封锁规则。</p>`},
 {word:'特殊格',title:'落点，会改变旅程',lead:'水把棋送回重生。点下面的格名，看看三个特殊落点。',detail:`<h2>记住 15、26、27</h2><p><b>15 · 重生</b><br>这里的棋受到保护。落水的棋，以及在终段被吃的棋，都回到这里。</p><p><b>26 · 幸福</b><br>这里的棋也受到保护。本版没有要求每枚棋必须先停在这一格。</p><p><b>27 · 水</b><br>只有落在这里才会返回 15 格，路过不触发。</p><p class="fine">图中 15 格保持空着。原规则没有说明返回时 15 被占怎么办，真实对局前请双方先约定。</p>`},
 {word:'终段',title:'终点前的相遇，有例外',lead:'选择最后三格中的一个，再让金棋到达那里。被吃的棋会回到重生。',detail:`<h2>不回原位，回重生</h2><p>28、29、30 格上的棋被吃时，返回 15 格，而不是与进攻棋交换。</p><p>例如从 25 走到 28：金棋留在 28，深色棋返回 15，25 变成空格。</p><h3>保护仍然有效</h3><p>最后三格如果存在相邻同色棋，仍然受保护。这一页特意使用一枚孤立的深色棋。</p><p class="fine">同样避开了 15 格已经被占的情况。</p>`},
 {word:'离场',title:'最后一步，要刚刚好',lead:'选一枚棋，再换换掷点。28、29、30 格，分别对应 3、2、1 步离场。',detail:`<h2>三个格，三个点数</h2><p>28 格上的棋掷到 3，可以离场；29 格需要 2；30 格需要 1。</p><p>这页可以反复试，不需要按固定顺序。已离场的棋不会再回到盘上，除非点击“重新摆放”。</p><h3>怎样获胜？</h3><div class="finish-rack" aria-hidden="true">${'<i class="pawn"></i>'.repeat(5)}</div><p>先将自己的 5 枚棋全部移出棋盘，就赢了。图里只演示最后三格的离场动作。</p><p class="fine">来源只明示了这三种离场方式。本手册不自行补充从更远位置大点数离场，或终段其他点数的移动规则。</p>`}
];
const pawn=(owner,protectedHere=false)=>`<span class="pawn ${owner===D?'dark':''} ${protectedHere?'protected':''}" aria-label="${owner===D?'深色棋':'金色棋'}${protectedHere?'，受保护':''}"></span>`;
function say(text,changed=false){$('message').textContent=text;$('message').className='message'+(changed?' changed':'');}
function focusCell(n,owner,tag='',protectedHere=false){return `<div class="focus-cell ${owner?'':'empty'} ${protectedHere?'protected-cell':''}"><span class="cell-identity"><b>${n}</b><span>${tag}</span></span>${owner?pawn(owner,protectedHere):'<span class="tag">空格</span>'}</div>`;}
function actionButton(action,label,secondary=false){return `<button class="${secondary?'small-button':'action-button'}" data-action="${action}">${label}</button>`;}
function renderRoute(){let html='<div class="portrait-board" role="group" aria-label="顺时针旋转90度的三行十列棋盘">';for(let n=1;n<=30;n++){const p=portraitPosition(n),names={15:'重生',26:'幸福',27:'水',28:'三',29:'二',30:'一'},direction=n===10||n===20?'←':n<=10||n>=21?'↓':'↑';html+=`<button class="square ${names[n]?'special':''} ${n===27?'water':''} ${n<=state.route?'visited':''} ${n===state.route?'current':''}" style="grid-row:${p.row+1};grid-column:${p.col+1}" data-square="${n}" aria-label="第 ${n} 格${names[n]?'，'+names[n]:''}${n===state.route?'，当前路线位置':''}" aria-pressed="${n===state.route}"><span class="number">${n}</span><span class="direction" aria-hidden="true">${direction}</span>${n===state.route?'<span class="route-pawn" aria-hidden="true"></span>':''}${names[n]?`<span class="square-label">${names[n]}</span>`:''}</button>`;}html+='</div><p class="scene-caption">右列向下 · 中列向上 · 左列向下</p><div class="controls">'+actionButton('routeStep','前进一格')+actionButton('routeReset','回到起点',true)+'</div>';$('scene').innerHTML=html;}
function renderSticks(){const r=scoreSticks(state.faces);$('scene').innerHTML=`<div class="throw-score">${r.score}<small>步</small></div><p class="extra-label">${r.extra?'走完，还能再掷一次':'走完，换对方'}</p><div class="sticks">${state.faces.map((v,i)=>`<button class="stick ${v?'':'dark'}" data-stick="${i}" aria-label="第 ${i+1} 根，${v?'浅面':'深面'}朝上，点击翻面" aria-pressed="${v}"><span>${v?'浅面':'深面'}</span></button>`).join('')}</div><div class="controls">${actionButton('randomThrow','一起掷一次')}</div><p class="scene-caption">${r.unpainted} 个浅面 · ${r.score} 步</p>`;}
function renderSwap(){const board=state.swap?move({12:G,16:D},12,4).board:{12:G,16:D};$('scene').innerHTML=`<p class="scene-subtitle">一次前进 4 步</p><div class="focus-track">${focusCell(12,board[12],'出发格')}${focusCell(13,null)}${focusCell(14,null)}${focusCell(15,null,'重生')}${focusCell(16,board[16],'落点')}</div><div class="controls">${actionButton('swap',state.swap?'回到原位':'让金棋走 4 步')}</div>`;}
function renderProtection(){let board={8:G,11:D,...(state.group?{12:D}:{})};if(state.groupMoved&&!state.group)board=move(board,8,3).board;$('scene').innerHTML=`<div class="tabs"><button data-group="yes" aria-pressed="${state.group}">有同伴</button><button data-group="no" aria-pressed="${!state.group}">独自一枚</button></div><div class="focus-track">${focusCell(8,board[8],'出发格')}${focusCell(9,null)}${focusCell(10,null)}${focusCell(11,board[11],'落点',state.group)}${focusCell(12,board[12],state.group?'同色相邻':'同伴已移开',state.group)}</div><div class="controls">${actionButton('protection',state.groupMoved?'回到原位':'尝试走到 11 格')}</div>`;}
function plaque(n,name,owner,type=''){return `<div class="special-plaque ${type}"><div><b>${n}</b><span>${name}</span></div>${owner?pawn(owner,type==='safe'):'<span>空格</span>'}</div>`;}
function renderSpecial(){const tabs=`<div class="tabs">${[['rebirth','15 重生'],['happiness','26 幸福'],['water','27 水']].map(([id,label])=>`<button data-special="${id}" aria-pressed="${state.special===id}">${label}</button>`).join('')}</div>`;let content;if(state.special==='water'){content=`<div class="special-pair">${plaque(24,'出发',state.water?null:G)}<div class="reentry-line">前进 3 步，落在水格</div>${plaque(27,'水',null,'water')}<div class="reentry-line">返回重生</div>${plaque(15,'重生',state.water?G:null,'safe')}</div><div class="controls">${actionButton('water',state.water?'再看一次':'走到水格')}</div>`;}else{const n=state.special==='rebirth'?15:26;content=`<div class="special-pair" style="margin-top:24px;margin-bottom:20px">${plaque(n,n===15?'重生':'幸福',G,'safe')}</div><p class="scene-subtitle">即使独自一枚，也不能被交换</p><p class="scene-caption">棋子周围的青色圈，表示保护</p>`;}$('scene').innerHTML=tabs+content;}
function renderEnding(){const target=state.ending,board=state.endMoved?move({25:G,[target]:D},25,target-25).board:{25:G,[target]:D};$('scene').innerHTML=`<div class="tabs">${[28,29,30].map(n=>`<button data-ending="${n}" aria-pressed="${target===n}">${n} 格</button>`).join('')}</div><div class="focus-track">${focusCell(25,board[25],'金棋出发')}<div class="spacer-note">前进 ${target-25} 步</div>${focusCell(target,board[target],'终段落点')}<div class="spacer-note">被吃的棋返回</div>${focusCell(15,board[15],'重生',!!board[15])}</div><div class="controls">${actionButton('ending',state.endMoved?'回到原位':'看看这次相遇')}</div>`;}
function renderExit(){$('scene').innerHTML=`<div class="exit-tiles">${[28,29,30].map(n=>`<button class="exit-tile ${state.exit===n?'active':''}" data-exit="${n}" aria-label="选择 ${n} 格，需要 ${31-n} 步离场${state.exited.has(n)?'，已经离场':''}" aria-pressed="${state.exit===n}"><b>${n}</b>${state.exited.has(n)?'<span class="gone">✓</span>':pawn(G)}<span>${state.exited.has(n)?'已离场':`需要 ${31-n} 步`}</span></button>`).join('')}</div><div class="number-control"><span>掷出</span>${[1,2,3].map(n=>`<button data-score="${n}" aria-pressed="${state.exitScore===n}">${n}</button>`).join('')}<span>步</span></div><div class="controls">${actionButton('exit','把棋移出棋盘')}${actionButton('exitReset','重新摆放',true)}</div>`;}
const renders=[renderRoute,renderSticks,renderSwap,renderProtection,renderSpecial,renderEnding,renderExit];
const messages=['点任意格查看路线；也可以一格一格走。','四根都朝深面，不是 0 步，而是 5 步。','金棋到 16，深色棋会回到金棋原来的 12 格。','有同伴时受保护；移开同伴，再试一次。','15 与 26 是安全格，27 是返回重生的水格。','这次的深色棋不会回 25，而会回到 15。','可以随意选棋和点数，观察什么时候能离场。'];
function renderPage(index,scroll=true){if(!Number.isInteger(index)||index<0||index>=pages.length)throw new Error('页码必须是 1 至 7');state.page=index;const p=pages[index];$('eyebrow').textContent=`${String(index+1).padStart(2,'0')} / 07 · ${p.word}`;$('pageTitle').textContent=p.title;$('pageLead').textContent=p.lead;$('details').innerHTML=p.detail;$('pageCount').textContent=`${String(index+1).padStart(2,'0')} / 07`;$('dots').innerHTML=pages.map((_,i)=>`<i class="${i===index?'active':''}"></i>`).join('');$('previous').disabled=index===0;$('next').disabled=index===pages.length-1;renders[index]();say(messages[index]);if(scroll){window.scrollTo({top:0,behavior:'instant'});$('main').focus({preventScroll:true});}}
function changePage(direction){const next=state.page+direction;if(next>=0&&next<pages.length)renderPage(next);}
function act(action){switch(action){case'routeStep':state.route=state.route===30?1:state.route+1;renderRoute();say(`来到 ${state.route} 格。${state.route===11?'从右列转入中列，开始向上。':state.route===21?'从中列转入左列，开始向下。':'路线按编号继续。'}`,true);break;case'routeReset':state.route=1;renderRoute();say('回到右上角的 1 格。');break;case'randomThrow':state.faces=Array.from(crypto.getRandomValues(new Uint8Array(4)),n=>!!(n%2));renderSticks();say('四根棒已经重新落定。也可以逐根点按翻面。',true);break;case'swap':state.swap=!state.swap;renderSwap();say(state.swap?'已经交换：金棋在 16，深色棋在 12。':'两枚棋回到示意的初始位置。',state.swap);break;case'protection':if(state.group){say('11 和 12 是相邻同色棋，受到保护；这一步不能交换。',true);}else{state.groupMoved=!state.groupMoved;renderProtection();say(state.groupMoved?'没有同色棋相邻，11 格的深色棋与金棋交换了。':'回到原位，可以再试一次。',state.groupMoved);}break;case'water':state.water=!state.water;renderSpecial();say(state.water?'金棋落到 27 后，已返回 15 格“重生”。':'金棋回到 24，可以再看一次落水。',state.water);break;case'ending':state.endMoved=!state.endMoved;renderEnding();say(state.endMoved?`金棋留在 ${state.ending} 格，深色棋回到 15。25 格空了。`:'恢复到相遇前的局面。',state.endMoved);break;case'exit':if(state.exited.has(state.exit)){say('这枚棋已经离场。可以选择另一枚，或重新摆放。');break;}if(state.exitScore!==31-state.exit){say(`${state.exit} 格需要 ${31-state.exit} 步离场。这一页只展示原文明示的离场条件。`);break;}const result=move({[state.exit]:G},state.exit,state.exitScore);if(result.ok&&result.event==='exit'){state.exited.add(state.exit);renderExit();say(`${state.exit} 格的金棋已凭 ${state.exitScore} 步离场。${state.exited.size===3?'这三枚示意棋都已离场；整局要带走自己的 5 枚。':''}`,true);}break;case'exitReset':state.exited.clear();renderExit();say('三枚棋重新摆回末尾，可以换个顺序试。');break;default:throw new Error('未知操作');}}
$('scene').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.action){act(d.action);return;}if(d.square){state.route=Number(d.square);renderRoute();say(`第 ${state.route} 格。${state.route<=10?'右列向下':state.route<=20?'中列向上':'左列向下'}。`);return;}if(d.stick!==undefined){const i=Number(d.stick);state.faces[i]=!state.faces[i];renderSticks();const r=scoreSticks(state.faces);say(`${r.unpainted} 个浅面，计 ${r.score} 步。${r.extra?'还能再掷一次。':'走完换对方。'}`,true);return;}if(d.group){state.group=d.group==='yes';state.groupMoved=false;renderProtection();say(state.group?'11 与 12 同色相邻，彼此保护。':'12 格的同伴已移开，11 格独自一枚。');return;}if(d.special){state.special=d.special;renderSpecial();say(state.special==='water'?'从 24 前进 3 步，会落到 27。':state.special==='rebirth'?'重生也是安全格，独立的棋同样受保护。':'幸福格受保护；本版不要求每枚棋必须停在这里。');return;}if(d.ending){state.ending=Number(d.ending);state.endMoved=false;renderEnding();say(`从 25 到 ${state.ending}，前进 ${state.ending-25} 步。`);return;}if(d.exit){state.exit=Number(d.exit);renderExit();say(`已选 ${state.exit} 格；它需要 ${31-state.exit} 步离场。`);return;}if(d.score){state.exitScore=Number(d.score);renderExit();say(`掷点设为 ${state.exitScore}。可以尝试移出选中的棋。`);}});
$('previous').onclick=()=>changePage(-1);$('next').onclick=()=>changePage(1);document.querySelector('.brand').onclick=e=>{e.preventDefault();renderPage(0);};for(const id of['rulesOpen','sourceOpen'])$(id).onclick=()=>$('rulesDialog').showModal();$('rulesClose').onclick=()=>$('rulesDialog').close();document.addEventListener('keydown',e=>{if($('rulesDialog').open||e.altKey||e.ctrlKey||e.metaKey)return;if(e.key==='ArrowRight'){e.preventDefault();changePage(1);}if(e.key==='ArrowLeft'){e.preventDefault();changePage(-1);}});
let touch=null;$('book').addEventListener('touchstart',e=>{if(e.touches.length!==1||e.target.closest('dialog')){touch=null;return;}touch={x:e.touches[0].clientX,y:e.touches[0].clientY,time:Date.now()};},{passive:true});$('book').addEventListener('touchend',e=>{if(!touch||!e.changedTouches.length)return;const t=e.changedTouches[0],direction=swipeDirection(t.clientX-touch.x,t.clientY-touch.y,Date.now()-touch.time);touch=null;if(direction)changePage(direction);},{passive:true});$('book').addEventListener('touchcancel',()=>{touch=null;},{passive:true});
renderPage(0,false);
function readState(){return {page:state.page+1,title:pages[state.page].title,route:state.route,throw:scoreSticks(state.faces),groupProtected:state.group,selectedFinalSquare:state.exit,exitScore:state.exitScore,exited:Array.from(state.exited),message:$('message').textContent};}
const ctx=document.modelContext;if(ctx?.registerTool){const life=new AbortController();const register=tool=>{try{Promise.resolve(ctx.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};register({name:'read_senet_handbook',description:'Read current Senet handbook page and interactive state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:readState});register({name:'open_senet_page',description:'Navigate to one of seven Senet knowledge pages, the same as horizontal paging.',inputSchema:{type:'object',properties:{page:{type:'integer',minimum:1,maximum:7}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({page})=>{renderPage(page-1);return readState();}});register({name:'flip_senet_sticks',description:'On the sticks page, flip one or more of the four sticks and recalculate the visible score.',inputSchema:{type:'object',properties:{sticks:{type:'array',items:{type:'integer',minimum:1,maximum:4},minItems:1,maxItems:4,uniqueItems:true}},required:['sticks'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({sticks})=>{if(state.page!==1)throw new Error('请先打开掷棒页');if(!Array.isArray(sticks)||!sticks.length||sticks.length>4||new Set(sticks).size!==sticks.length||sticks.some(n=>!Number.isInteger(n)||n<1||n>4))throw new Error('掷棒编号必须为不重复的1至4');for(const n of sticks)state.faces[n-1]=!state.faces[n-1];renderSticks();return readState();}});window.addEventListener('pagehide',()=>life.abort(),{once:true});}
